[package]
name = "ektaon"
version = "1.0.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
csv = "1.3"
serde = { version = "1.0", features = ["derive"] }
regex = "1"
once_cell = "1"
# Error
thiserror = "1.0"
